#!/bin/bash

set -x

# (re)install mapping service directories on webserver and cluster.
# Is semi-destructive (removes empty directories before installing)
# so creates a race condition if there are jobs running. So, it's 
# ill advised to reinstall with jobs in the queue.

#
CLUSTER_USER=mheiges
CLUSTER=192.168.149.133
CLUSTER_PREFIX=/scratch/jcklab/eupath
RELEASE=5
SITE=integrate

WEBSERVER_PREFIX=/var/www/Common

WS_BLAST_DIR=/var/www/Common/devSiteFilesMirror/webServices/OrthoMCL/release-$RELEASE/blast

# standard configuration, normally not changed
TOP_DIR=orthomcl-mapping-service

###############################################################################
# FUNCTIONS

function abort() {
  msg=$1
  echo
  echo -e '\E[;31m'"\033[1m$1\033[0m"
  exit 1
}

function remote_cmd_without_env() {
  sshcmd="ssh $CLUSTER_USER@$CLUSTER"
  $sshcmd $1 >/dev/null 2>&1
}


###############################################################################
# WEBSERVER


W_WORKDIR="$WEBSERVER_PREFIX/$TOP_DIR/$SITE/queues"

# remove empty directories - an attempt to clean up
# any directory obsolescence without losing any data
# in the pipeline
find "$WEBSERVER_PREFIX"/"$TOP_DIR"/"$SITE" -depth -type d -empty -exec rmdir {} \;

mkdir -p "$W_WORKDIR"/"$CLUSTER"/{results,newJobs}

mkdir -p "$W_WORKDIR"/"$CLUSTER"/{phase1,phase2}/{runningJobs,failedJobs}

chmod -R g+rw "$W_WORKDIR"
chmod 0777 "$W_WORKDIR"/"$CLUSTER"/newJobs

###############################################################################
# CLUSTER

C_WORKDIR="$CLUSTER_PREFIX/$TOP_DIR/$SITE/queues"
C_BLAST_DIR="$CLUSTER_PREFIX/$TOP_DIR/db/release-$RELEASE"

remote_cmd_without_env \
    "find \"$CLUSTER_PREFIX\"/\"$TOP_DIR\"/\"$SITE\" -depth -type d -empty -exec rmdir {} \\;"

remote_cmd_without_env \
    "mkdir -p \"$C_WORKDIR\"/\"$CLUSTER\"/{results,newJobs}"

remote_cmd_without_env \
    "mkdir -p \"$C_WORKDIR\"/\"$CLUSTER\"/{phase1,phase2}/{runningJobs,failedJobs}"

remote_cmd_without_env \
    "chmod -R g+rw \"$C_WORKDIR\""
    
remote_cmd_without_env \
    "mkdir -p \"$C_BLAST_DIR\""
rsync -a --delete $WS_BLAST_DIR/ $CLUSTER_USER@$CLUSTER:$C_BLAST_DIR
